language: node_js
node_js:
  - '8'
install:
  - npm install
before_deploy:
  - npm run build
deploy:
  provider: script
  script: DEPLOY_BUCKET=$AWS_S3_BUCKET CLOUDFRONT_DISTRIBUTION_ID=$AWS_CLOUDFRONT_DISTRO_ID npm run deploy
  skip_cleanup: true
  # on:
    # branch: master
    # tags: true
