language: node_js
node_js:
  - '8'
install:
  - npm install
before_deploy:
  - npm run build
deploy:
  provider: script
  script: DEPLOY_BUCKET=$AWS_S3_BUCKET npm run deploy
  # on:
    # branch: master
    # tags: true
after_deploy:
  - pip install --user awscli
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRO_ID --paths /
