language: node_js
node_js:
  - '8'
install:
  - npm install
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_S3_BUCKET"
  local_dir: build
  skip_cleanup: true
  acl: private
  on:
    branch: master
    tags: true
